#!/bin/sh
brew update && brew upgrade
brew tap homebrew/cask-fonts
brew install grep gzip tmux curl wget tree bash bash-completion@2 shellcheck less openssh python rsync unzip vim lynx go gh pandoc nmap jq yq watch font-hack-nerd-font ranger lolcat figlet fzf ripgrep
brew install --cask google-chrome iterm2 visual-studio-code dropbox yandex-disk google-drive docker postman telegram discord transmission vlc iina pgadmin4 keyboardcleantool openvpn-connect zoom betterzip usb-overdrive anydesk dbeaver-community podman-desktop
