#!/bin/sh

brew install grep gzip tmux curl wget bash less openssh python rsync unzip vim bash lynx golang gh pandoc nmap jq watch

brew install --cask google-chrome iterm2 visual-studio-code dropbox docker postman telegram
