#!/bin/sh
set -e

# mkdir -p is not POSIX compliant
[ ! -d ~/.local ] && mkdir ~/.local
[ ! -d ~/.local/bin ] && mkdir ~/.local/bin

ROOT_FILES='.bashrc
.dircolors
.inputrc
.profile
.bash_profile
.gitconfig
.gitattributes'

for file in $ROOT_FILES; do
	ROOT_FILE_PATH=$(readlink "${HOME}/$file")
	CURRENT_FILE_PATH="${PWD}/$file"
	HOME_FILE_PATH="${HOME}/$file"

	if [ -L "$HOME_FILE_PATH" ] && [ "$ROOT_FILE_PATH" = "$CURRENT_FILE_PATH" ]; then
		echo "$HOME_FILE_PATH already linked, skip"
		continue
	fi

	if [ -L "$HOME_FILE_PATH" ] && [ "$ROOT_FILE_PATH" = "$CURRENT_FILE_PATH" ]; then
		echo "$HOME_FILE_PATH already linked, skip"
		continue
	elif [ -e "$HOME_FILE_PATH" ] || [ -d "$HOME_FILE_PATH" ]; then
		mv "$HOME_FILE_PATH" "$HOME_FILE_PATH".back
		echo "$HOME_FILE_PATH moved to $HOME_FILE_PATH.back"
	fi

  ln -sf "$CURRENT_FILE_PATH" "$HOME_FILE_PATH"
done

for i in vim tmux; do
  cd $i && ./setup
  cd -
done