#!/bin/sh

# run from root dir
SCRIPT_ROOT_DIR=$(dirname "$0")
cd "$SCRIPT_ROOT_DIR" || exit

# mkdir -p is not POSIX compliant
[ ! -d ~/.local ] && mkdir ~/.local
[ ! -d ~/.local/bin ] && mkdir ~/.local/bin

ROOT_FILES='.bashrc
.dircolors
.inputrc
.aliases
.profile'

for file in $ROOT_FILES; do
	ROOT_FILE_PATH=$(readlink "${HOME}/$file")
	CURRENT_FILE_PATH="${PWD}/$file"
	HOME_FILE_PATH="${HOME}/$file"

	if [ -L "$HOME_FILE_PATH" ] && [ "$ROOT_FILE_PATH" = "$CURRENT_FILE_PATH" ]; then
		echo "$HOME_FILE_PATH already linked, skip"
		continue
	elif [ -e "$HOME_FILE_PATH" ]; then
		mv "$HOME_FILE_PATH" "$HOME_FILE_PATH".back
		echo "$HOME_FILE_PATH moved to $HOME_FILE_PATH.back"
	fi

  ln -sf "$CURRENT_FILE_PATH" "$HOME_FILE_PATH"
done

if [ ! -e "${HOME}/.gitconfig" ]; then
    cp "${PWD}/.gitconfig" "${HOME}/.gitconfig"
fi

if [ ! -e "${HOME}/.gitattributes" ]; then
    cp "${PWD}/.gitattributes" "${HOME}/.gitattributes"
fi

ln -sf "$PWD/.profile" "$HOME/.bash_profile"

[ ! -d ~/.ssh ] && mkdir ~/.ssh
ln -sf "$PWD/.ssh_config" "$HOME/.ssh/config"

for i in vim tmux lynx gh docker podman; do
  cd $i && ./setup
  cd -
done
