#!/bin/sh

sudo apt-get install -y podman
os=$(uname -s | tr '[:upper:]' '[:lower:]')
arch=$(dpkg --print-architecture)
sudo curl -L "https://github.com/containers/gvisor-tap-vsock/releases/latest/download/gvproxy-$os-$arch" -o "/usr/libexec/podman/gvproxy" && sudo chmod +x /usr/libexec/podman/gvproxy
sudo chmod 4755 /usr/bin/newgidmap
sudo chmod 4755 /usr/bin/newuidmap
