#!/bin/sh
set -e
latest="https://api.github.com/repos/sharkdp/hyperfine/releases/latest"
ver=$(curl -sS "$latest" | jq -r .zipball_url) && test -n "$ver"
arch=$(dpkg --print-architecture)
ver=${ver##*/} && deb="hyperfine_${ver#v}_${arch}.deb"
url="https://github.com/sharkdp/hyperfine/releases/download/$ver/$deb"
curl -sSLO "$url" && sudo dpkg -i ./*.deb
