#!/usr/bin/env bash

rm -rf "$HOME/.config/nvim"
rm -rf "$HOME/.local/share/nvim"
rm -rf "$HOME/.local/state/nvim"
rm -rf "$HOME/.cache/nvim"

mkdir -p "$HOME/.config/nvim/lua"
ln -sf "$PWD/.config/nvim/init.lua" "$HOME/.config/nvim/init.lua"
ln -sf "$PWD/.config/nvim/lua/config" "$HOME/.config/nvim/lua/config"
ln -sf "$PWD/.config/nvim/lua/plugins" "$HOME/.config/nvim/lua/plugins"
