#!/usr/bin/env bash

_have() { type "$1" &>/dev/null; }
! _have mods && echo "requires charmbracelet/mods" && exit 1

export OPENAI_API_KEY="_"

if [ -e "$HOME/.config/gpt/token" ]; then
    declare OPENAI_API_KEY
    OPENAI_API_KEY="$(head -1 "$HOME/.config/gpt/token")"
    export OPENAI_API_KEY
fi

#if test -t 0; then
#  if _have glow; then
#    mods --api "cjk-gpt" --model "gpt" --status-text "Ummm" -f "$*" | glow
#  else
    mods --api "cjk-gpt" --model "gpt" --status-text "Ummm" "$*"
#  fi
#else
#  mods --quiet "$*" | sed -E 's,[?25l [0D[2K[?25h[?1002l[?1003l,,g'
  # |sed 's/\x1B\[[0-9;\?]*[a-zA-Z]//g'
#fi
