#!/bin/sh
set -e

ln -sf "$PWD/.config/fish" "$HOME/.config/fish"
ln -sf "$PWD/.config/omf" "$HOME/.config/omf"
ln -sf "$PWD/.config/ranger" "$HOME/.config/ranger"
ln -sf "$PWD/.config/htop" "$HOME/.config/htop"
